

name: manual run

on:
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:      

      - uses: Platane/snk@v3
        with:
          github_user_name: SoloXeniya
          outputs: |
           dist/docker/github-contribution-grid-snake-dark.gif?color_snake=orange&color_dots=%23000000,%238dbdff,%2364a1f4,%234b91f1,%233c7dd9
           dist/docker/github-contribution-grid-snake-dark.svg?color_snake=orange&color_dots=%23000000,%238dbdff,%2364a1f4,%234b91f1,%233c7dd9
           
           dist/docker/github-contribution-grid-snake-dark.svg?color_snake=orange&color_dots=%23000000,%001F33,%003366,%0056A7,%0077B5
           dist/docker/github-contribution-grid-snake-dark.svg?color_snake=orange


      - name: ensure the generated file exists
        run: |
          ls dist
          test -f dist/docker/github-contribution-grid-snake-dark.gif
           test -f dist/docker/github-contribution-grid-snake-dark.svg

      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
          
