
name: generate-snake

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:      
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: SoloXeniya
          outputs: |
            dist/docker/github-contribution-grid-snake-dark.svg?color_snake=orange 
            
      - name: Ensure the generated files exist
        run: |
          ls -R dist
          test -f dist/docker/github-contribution-grid-snake-dark.svg

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
